/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef CHARPORTTABLE_H
#define CHARPORTTABLE_H

/* function declarations */
void init_charPortTable(void);
void initialize_table_charPortTable(void);
Netsnmp_Node_Handler charPortTable_handler;
Netsnmp_First_Data_Point  charPortTable_get_first_data_point;
Netsnmp_Next_Data_Point   charPortTable_get_next_data_point;

/* column number definitions for table charPortTable */
#define COLUMN_CHARPORTINDEX		1
#define COLUMN_CHARPORTNAME		2
#define COLUMN_CHARPORTTYPE		3
#define COLUMN_CHARPORTHARDWARE		4
#define COLUMN_CHARPORTRESET		5
#define COLUMN_CHARPORTADMINSTATUS		6
#define COLUMN_CHARPORTOPERSTATUS		7
#define COLUMN_CHARPORTLASTCHANGE		8
#define COLUMN_CHARPORTINFLOWTYPE		9
#define COLUMN_CHARPORTOUTFLOWTYPE		10
#define COLUMN_CHARPORTINFLOWSTATE		11
#define COLUMN_CHARPORTOUTFLOWSTATE		12
#define COLUMN_CHARPORTINCHARACTERS		13
#define COLUMN_CHARPORTOUTCHARACTERS		14
#define COLUMN_CHARPORTADMINORIGIN		15
#define COLUMN_CHARPORTSESSIONMAXIMUM		16
#define COLUMN_CHARPORTSESSIONNUMBER		17
#define COLUMN_CHARPORTSESSIONINDEX		18

/*Port OPeration Status definitions*/
#define PORT_FUNC_UP			1
#define PORT_FUNC_DOWN			2
#define PORT_FUNC_MAINTENANCE		3
#define PORT_FUNC_ABSENT		4
#define PORT_FUNC_ACTIVE		5
#
/*Port In/Out Flow Type definitions*/
#define PORT_FLOW_TYPE_NONE		1
#define PORT_FLOW_TYPE_SW		2
#define PORT_FLOW_TYPE_HW		3
#define PORT_FLOW_TYPE_CTSRTS		4
#define PORT_FLOW_TYPE_DSRDTR		5

#endif /* CHARPORTTABLE_H */
