/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DIPRODUCT_H
#define DIPRODUCT_H

/* function declarations */
void init_diProduct(void);
Netsnmp_Node_Handler handle_diProduct;

/*Model Name definitions*/
#define SNMP_OID_MODEL_LENGTH	37
#define SNMP_OID_MODEL_100S	"DataCaptor Terminal Server 100 Series"
#define SNMP_OID_MODEL_400S	"DataCaptor Terminal Server 400 Series"
#define SNMP_OID_MODEL_800S	"DataCaptor Terminal Server 800 Series"


#endif /* DIPRODUCT_H */
