/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef GENERALTYPE_H
#define GENERALTYPE_H

/* function declarations */
void init_generalType(void);
Netsnmp_Node_Handler handle_generalType;

/*Type Name definition*/
#define SNMP_OID_TYPE_LENGTH	7
#define SNMP_OID_TYPE_1PORT	"Axon110"
#define SNMP_OID_TYPE_4PORT	"Axon410"
#define SNMP_OID_TYPE_8PORT	"Axon810"

#endif /* GENERALTYPE_H */
