/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "rs232AsyncPortTable.h"

/* create a new row in the (unsorted) table */
struct rs232AsyncPortTable_entry *
rs232AsyncPortTable_createEntry(long  rs232AsyncPortIndex);
/* remove a row from the table */
void rs232AsyncPortTable_removeEntry( struct rs232AsyncPortTable_entry *entry );



/* Typical data structure for a row entry */
struct rs232AsyncPortTable_entry {
    /* Index values */
    long rs232AsyncPortIndex;

    /* Column values */
    long rs232AsyncPortBits;
    long old_rs232AsyncPortBits;
    long rs232AsyncPortStopBits;
    long old_rs232AsyncPortStopBits;
    long rs232AsyncPortParity;
    long old_rs232AsyncPortParity;
    long rs232AsyncPortAutobaud;
    long old_rs232AsyncPortAutobaud;
    u_long rs232AsyncPortParityErrs;
    u_long rs232AsyncPortFramingErrs;
    u_long rs232AsyncPortOverrunErrs;

    /* Illustrate using a simple linked list */
    int   valid;
    struct rs232AsyncPortTable_entry *next;
};


/** Initializes the rs232AsyncPortTable module */
void
init_rs232AsyncPortTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_rs232AsyncPortTable();
}

/** Initialize the rs232AsyncPortTable table by defining its contents and how it's structured */
void
initialize_table_rs232AsyncPortTable(void)
{
    const oid rs232AsyncPortTable_oid[] = {1,3,6,1,2,1,10,33,3};
    const size_t rs232AsyncPortTable_oid_len   = OID_LENGTH(rs232AsyncPortTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("rs232AsyncPortTable:init", "initializing table rs232AsyncPortTable\n"));

    reg = netsnmp_create_handler_registration(
              "rs232AsyncPortTable",     rs232AsyncPortTable_handler,
              rs232AsyncPortTable_oid, rs232AsyncPortTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: rs232AsyncPortIndex */
                           0);
    table_info->min_column = COLUMN_RS232ASYNCPORTINDEX;
    table_info->max_column = COLUMN_RS232ASYNCPORTOVERRUNERRS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = rs232AsyncPortTable_get_first_data_point;
    iinfo->get_next_data_point  = rs232AsyncPortTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    struct rs232AsyncPortTable_entry *entry;
    //PortIndex 1
    entry = rs232AsyncPortTable_createEntry(1);
    entry->rs232AsyncPortBits = RS232_CHARACTER_8BITS;
    entry->rs232AsyncPortStopBits = RS232_STOP_1BITS;
    entry->rs232AsyncPortParity = RS232_POLARITY_NONE;
    //PortIndex 2
    entry = rs232AsyncPortTable_createEntry(2);
    entry->rs232AsyncPortBits = RS232_CHARACTER_8BITS;
    entry->rs232AsyncPortStopBits = RS232_STOP_1BITS;
    entry->rs232AsyncPortParity = RS232_POLARITY_NONE;
    //PortIndex 3
    entry = rs232AsyncPortTable_createEntry(3);
    entry->rs232AsyncPortBits = RS232_CHARACTER_8BITS;
    entry->rs232AsyncPortStopBits = RS232_STOP_1BITS;
    entry->rs232AsyncPortParity = RS232_POLARITY_NONE;
    //PortIndex 4
    entry = rs232AsyncPortTable_createEntry(4);
    entry->rs232AsyncPortBits = RS232_CHARACTER_8BITS;
    entry->rs232AsyncPortStopBits = RS232_STOP_1BITS;
    entry->rs232AsyncPortParity = RS232_POLARITY_NONE;
}

struct rs232AsyncPortTable_entry  *rs232AsyncPortTable_head;

/* create a new row in the (unsorted) table */
struct rs232AsyncPortTable_entry *
rs232AsyncPortTable_createEntry(long  rs232AsyncPortIndex) {
    struct rs232AsyncPortTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct rs232AsyncPortTable_entry);
    if (!entry)
        return NULL;

    entry->rs232AsyncPortIndex = rs232AsyncPortIndex;
    entry->next = rs232AsyncPortTable_head;
    rs232AsyncPortTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
rs232AsyncPortTable_removeEntry( struct rs232AsyncPortTable_entry *entry ) {
    struct rs232AsyncPortTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = rs232AsyncPortTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        rs232AsyncPortTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
rs232AsyncPortTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = rs232AsyncPortTable_head;
    return rs232AsyncPortTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
rs232AsyncPortTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct rs232AsyncPortTable_entry *entry = (struct rs232AsyncPortTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->rs232AsyncPortIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the rs232AsyncPortTable table */
int
rs232AsyncPortTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    int ret = 0;
    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct rs232AsyncPortTable_entry          *table_entry;

    DEBUGMSGTL(("rs232AsyncPortTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232AsyncPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232ASYNCPORTBITS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232AsyncPortBits);
                break;
            case COLUMN_RS232ASYNCPORTSTOPBITS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232AsyncPortStopBits);
                break;
            case COLUMN_RS232ASYNCPORTPARITY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232AsyncPortParity);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232AsyncPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232ASYNCPORTBITS:
                //Check if the table entry is valid
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                else if (*request->requestvb->val.integer == RS232_CHARACTER_7BITS ||
                         *request->requestvb->val.integer == RS232_CHARACTER_8BITS)
                {
                    //Value fulfill the requirement
                }
                else
                {
                    ret = SNMP_ERR_WRONGVALUE; 
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232ASYNCPORTSTOPBITS:
                //Check if the table entry is valid
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                else if (*request->requestvb->val.integer == RS232_STOP_1BITS ||
                         *request->requestvb->val.integer == RS232_STOP_2BITS)
                {
                    //Value fulfill the requirement
                }
                else
                {
                    ret = SNMP_ERR_WRONGVALUE;
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232ASYNCPORTPARITY:
                //Check if the table entry is valid
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                else if (*request->requestvb->val.integer == RS232_POLARITY_NONE ||
                         *request->requestvb->val.integer == RS232_POLARITY_ODD ||
                         *request->requestvb->val.integer == RS232_POLARITY_EVEN)
                {
                    //Value fulfill the requirement
                }
                else
                {
                    ret = SNMP_ERR_WRONGVALUE;
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }

                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232AsyncPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232ASYNCPORTBITS:
                table_entry->old_rs232AsyncPortBits = table_entry->rs232AsyncPortBits;
                table_entry->rs232AsyncPortBits     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232ASYNCPORTSTOPBITS:
                table_entry->old_rs232AsyncPortStopBits = table_entry->rs232AsyncPortStopBits;
                table_entry->rs232AsyncPortStopBits     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232ASYNCPORTPARITY:
                table_entry->old_rs232AsyncPortParity = table_entry->rs232AsyncPortParity;
                table_entry->rs232AsyncPortParity     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232AsyncPortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232ASYNCPORTBITS:
                table_entry->rs232AsyncPortBits     = table_entry->old_rs232AsyncPortBits;
                table_entry->old_rs232AsyncPortBits = 0;
                break;
            case COLUMN_RS232ASYNCPORTSTOPBITS:
                table_entry->rs232AsyncPortStopBits     = table_entry->old_rs232AsyncPortStopBits;
                table_entry->old_rs232AsyncPortStopBits = 0;
                break;
            case COLUMN_RS232ASYNCPORTPARITY:
                table_entry->rs232AsyncPortParity     = table_entry->old_rs232AsyncPortParity;
                table_entry->old_rs232AsyncPortParity = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
