/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef RS232NUMBER_H
#define RS232NUMBER_H

/* function declarations */
void init_rs232Number(void);

/*NUmber of RS232 Ports definition*/
#define RS232_1PORTS                 1
#define RS232_4PORTS                 4
#define RS232_8PORTS                 8

#endif /* RS232NUMBER_H */
