/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "rs232PortTable.h"


/* create a new row in the (unsorted) table */
struct rs232PortTable_entry *
rs232PortTable_createEntry(long rs232PortIndex);
/* remove a row from the table */
void rs232PortTable_removeEntry( struct rs232PortTable_entry *entry );


/** Initializes the rs232PortTable module */
void
init_rs232PortTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_rs232PortTable();
}


//  # Determine the first/last column names
/* Typical data structure for a row entry */
struct rs232PortTable_entry {
    /* Index values */
    long rs232PortIndex;

    /* Column values */
    long rs232PortType;
    long rs232PortInSigNumber;
    long rs232PortOutSigNumber;
    long rs232PortInSpeed;
    long old_rs232PortInSpeed;
    long rs232PortOutSpeed;
    long old_rs232PortOutSpeed;
    long rs232PortInFlowType;
    long old_rs232PortInFlowType;
    long rs232PortOutFlowType;
    long old_rs232PortOutFlowType;

    /* Illustrate using a simple linked list */
    int   valid;
    struct rs232PortTable_entry *next;
};


/** Initialize the rs232PortTable table by defining its contents and how it's structured */
void
initialize_table_rs232PortTable(void)
{
    const oid rs232PortTable_oid[] = {1,3,6,1,2,1,10,33,2};
    const size_t rs232PortTable_oid_len   = OID_LENGTH(rs232PortTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("rs232PortTable:init", "initializing table rs232PortTable\n"));

    reg = netsnmp_create_handler_registration(
              "rs232PortTable",     rs232PortTable_handler,
              rs232PortTable_oid, rs232PortTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: rs232PortIndex */
                           0);
    table_info->min_column = COLUMN_RS232PORTINDEX;
    table_info->max_column = COLUMN_RS232PORTOUTFLOWTYPE;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = rs232PortTable_get_first_data_point;
    iinfo->get_next_data_point  = rs232PortTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    struct rs232PortTable_entry *entry;
    //PortIndex 1
    entry = rs232PortTable_createEntry(1);
    entry->rs232PortInSpeed = RS232_BAUDRATE_19200;
    entry->rs232PortOutSpeed = RS232_BAUDRATE_19200;
    entry->rs232PortInFlowType = RS232_FLOWCTL_NONE;
    entry->rs232PortOutFlowType = RS232_FLOWCTL_NONE;
    //PortIndex 2
    entry = rs232PortTable_createEntry(2);
    entry->rs232PortInSpeed = RS232_BAUDRATE_19200;
    entry->rs232PortOutSpeed = RS232_BAUDRATE_19200;
    entry->rs232PortInFlowType = RS232_FLOWCTL_NONE;
    entry->rs232PortOutFlowType = RS232_FLOWCTL_NONE;
    //PortIndex 3
    entry = rs232PortTable_createEntry(3);
    entry->rs232PortInSpeed = RS232_BAUDRATE_19200;
    entry->rs232PortOutSpeed = RS232_BAUDRATE_19200;
    entry->rs232PortInFlowType = RS232_FLOWCTL_NONE;
    entry->rs232PortOutFlowType = RS232_FLOWCTL_NONE;
    //PortIndex 4
    entry = rs232PortTable_createEntry(4);
    entry->rs232PortInSpeed = RS232_BAUDRATE_19200;
    entry->rs232PortOutSpeed = RS232_BAUDRATE_19200;
    entry->rs232PortInFlowType = RS232_FLOWCTL_NONE;
    entry->rs232PortOutFlowType = RS232_FLOWCTL_NONE;
    
}


struct rs232PortTable_entry  *rs232PortTable_head;

/* create a new row in the (unsorted) table */
struct rs232PortTable_entry *
rs232PortTable_createEntry(long rs232PortIndex) {
    struct rs232PortTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct rs232PortTable_entry);
    if (!entry)
        return NULL;

    entry->rs232PortIndex = rs232PortIndex;
    entry->next = rs232PortTable_head;
    rs232PortTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
rs232PortTable_removeEntry( struct rs232PortTable_entry *entry ) {
    struct rs232PortTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = rs232PortTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        rs232PortTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
rs232PortTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = rs232PortTable_head;
    return rs232PortTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
rs232PortTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct rs232PortTable_entry *entry = (struct rs232PortTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->rs232PortIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the rs232PortTable table */
int
rs232PortTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    int ret = 0;
    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct rs232PortTable_entry          *table_entry;

    DEBUGMSGTL(("rs232PortTable:handler", "Processing request (%d)\n", reqinfo->mode));


    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232PortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
   
 
            switch (table_info->colnum) {
            case COLUMN_RS232PORTINSPEED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232PortInSpeed);
                break;
            case COLUMN_RS232PORTOUTSPEED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232PortOutSpeed);
                break;
            case COLUMN_RS232PORTINFLOWTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232PortInFlowType);
                break;
            case COLUMN_RS232PORTOUTFLOWTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rs232PortOutFlowType);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232PortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232PORTINSPEED:
                //Check if the table entry is valid
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                else if (*request->requestvb->val.integer == RS232_BAUDRATE_300 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_600 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_1200 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_2400 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_4800 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_9600 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_19200 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_38400 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_57600 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_115200 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_230400)
                {
                    //Value fulfill the requirement
                }
                else
                {
                    ret = SNMP_ERR_WRONGVALUE;
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232PORTOUTSPEED:
                //Check if the table entry is valid
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                else if (*request->requestvb->val.integer == RS232_BAUDRATE_300 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_600 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_1200 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_2400 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_4800 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_9600 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_19200 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_38400 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_57600 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_115200 ||
                         *request->requestvb->val.integer == RS232_BAUDRATE_230400)
                {
                    //Value fulfill the requirement
                }
                else
                {
                    ret = SNMP_ERR_WRONGVALUE;
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232PORTINFLOWTYPE:
                //Check if the table entry is valid
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                else if (*request->requestvb->val.integer == RS232_FLOWCTL_NONE ||
                         *request->requestvb->val.integer == RS232_FLOWCTL_CTSRTS)
                {
                    //Value fulfill the requirement
                }
                else
                {
                    ret = SNMP_ERR_WRONGVALUE;
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RS232PORTOUTFLOWTYPE:
                //Check if the table entry is valid
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                else if (*request->requestvb->val.integer == RS232_FLOWCTL_NONE ||
                         *request->requestvb->val.integer == RS232_FLOWCTL_CTSRTS)
                {
                    //Value fulfill the requirement
                }
                else
                {
                    ret = SNMP_ERR_WRONGVALUE;
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232PortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232PORTINSPEED:
                table_entry->old_rs232PortInSpeed = table_entry->rs232PortInSpeed;
                table_entry->rs232PortInSpeed     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232PORTOUTSPEED:
                table_entry->old_rs232PortOutSpeed = table_entry->rs232PortOutSpeed;
                table_entry->rs232PortOutSpeed     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232PORTINFLOWTYPE:
                table_entry->old_rs232PortInFlowType = table_entry->rs232PortInFlowType;
                table_entry->rs232PortInFlowType     = *request->requestvb->val.integer;
                break;
            case COLUMN_RS232PORTOUTFLOWTYPE:
                table_entry->old_rs232PortOutFlowType = table_entry->rs232PortOutFlowType;
                table_entry->rs232PortOutFlowType     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct rs232PortTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RS232PORTINSPEED:
                table_entry->rs232PortInSpeed     = table_entry->old_rs232PortInSpeed;
                table_entry->old_rs232PortInSpeed = 0;
                break;
            case COLUMN_RS232PORTOUTSPEED:
                table_entry->rs232PortOutSpeed     = table_entry->old_rs232PortOutSpeed;
                table_entry->old_rs232PortOutSpeed = 0;
                break;
            case COLUMN_RS232PORTINFLOWTYPE:
                table_entry->rs232PortInFlowType     = table_entry->old_rs232PortInFlowType;
                table_entry->old_rs232PortInFlowType = 0;
                break;
            case COLUMN_RS232PORTOUTFLOWTYPE:
                table_entry->rs232PortOutFlowType     = table_entry->old_rs232PortOutFlowType;
                table_entry->old_rs232PortOutFlowType = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
