/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef RS232PORTTABLE_H
#define RS232PORTTABLE_H

/* function declarations */
void init_rs232PortTable(void);
void initialize_table_rs232PortTable(void);
Netsnmp_Node_Handler rs232PortTable_handler;
Netsnmp_First_Data_Point  rs232PortTable_get_first_data_point;
Netsnmp_Next_Data_Point   rs232PortTable_get_next_data_point;

/* column number definitions for table rs232PortTable */
#define COLUMN_RS232PORTINDEX		        1
#define COLUMN_RS232PORTTYPE		        2
#define COLUMN_RS232PORTINSIGNUMBER		3
#define COLUMN_RS232PORTOUTSIGNUMBER		4
#define COLUMN_RS232PORTINSPEED		        5
#define COLUMN_RS232PORTOUTSPEED		6
#define COLUMN_RS232PORTINFLOWTYPE		7
#define COLUMN_RS232PORTOUTFLOWTYPE		8


/*RS232 Baud Rate definitions*/
#define RS232_BAUDRATE_300                      300
#define RS232_BAUDRATE_600                      600
#define RS232_BAUDRATE_1200                     1200
#define RS232_BAUDRATE_2400                     2400
#define RS232_BAUDRATE_4800                     4800
#define RS232_BAUDRATE_9600                     9600
#define RS232_BAUDRATE_19200                    19200
#define RS232_BAUDRATE_38400                    38400
#define RS232_BAUDRATE_57600                    57600
#define RS232_BAUDRATE_115200                   115200
#define RS232_BAUDRATE_230400                   230400

/*RS232 Flow Control definitions*/
#define RS232_FLOWCTL_NONE                      1
#define RS232_FLOWCTL_CTSRTS                    2

#endif /* RS232PORTTABLE_H */
